// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM_Server.Data;

#nullable disable

namespace PM_Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240807190046_AddSocioEconomicAssessment")]
    partial class AddSocioEconomicAssessment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PM_DataAccess.GeneInfo.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NationalityCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3704),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3699),
                            NationalityCode = new Guid("b7f59154-e80e-46d2-afbd-f503b14864be"),
                            NationalityName = "Afghan"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3715),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3711),
                            NationalityCode = new Guid("322f9f7e-0924-4283-9735-eb6fe521cc26"),
                            NationalityName = "Syrian"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3725),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3721),
                            NationalityCode = new Guid("cdf9d183-cc72-4ace-8173-c214df0326f7"),
                            NationalityName = "Palestinian"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3734),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3731),
                            NationalityCode = new Guid("0aa51782-8e03-4b80-9fa0-5cca399932f6"),
                            NationalityName = "Lebanese"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3807),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3803),
                            NationalityCode = new Guid("dd67a808-a874-4997-84a0-a6a874fe87cc"),
                            NationalityName = "Egyptian"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3817),
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3814),
                            NationalityCode = new Guid("4c4d6b73-2e65-414b-b081-a53860aa8122"),
                            NationalityName = "Iraqi"
                        });
                });

            modelBuilder.Entity("PM_DataAccess.PatientClasses.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferrerID")
                        .HasColumnType("int");

                    b.Property<int?>("SocialWorkerID")
                        .HasColumnType("int");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.HasIndex("ReferrerID");

                    b.HasIndex("SocialWorkerID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PM_DataAccess.Referrer.NGOClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NGOs");
                });

            modelBuilder.Entity("PM_DataAccess.SEA.SocioeconomicAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbilityToAffordEssentialNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisabilityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabilitySeverity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabilityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHealthInsurance")
                        .HasColumnType("bit");

                    b.Property<string>("HousingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HousingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncomeSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadOfHousehold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<bool>("MOSARegistered")
                        .HasColumnType("bit");

                    b.Property<string>("MOSARegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("NationalityID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDependents")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfFamilyMembers")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OtherRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("OtherRegistrationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<Guid>("SocioeconomicAssessmentCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurgeryRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UNCHRRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("UNCHRRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UNRWARegistered")
                        .HasColumnType("bit");

                    b.Property<string>("UNRWARegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingFamilyMembers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalityID");

                    b.HasIndex("PatientID");

                    b.ToTable("SEAssessments");
                });

            modelBuilder.Entity("PM_DataAccess.StagesClasses.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActualAssignee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentStage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNextStage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageGroupParent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageStatusID")
                        .HasColumnType("int");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("PM_DataAccess.StagesClasses.StageStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StageStatuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3410),
                            Description = "",
                            Icon = "Pending",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3406),
                            Status = "Pending"
                        },
                        new
                        {
                            ID = 2,
                            Color = "Primary",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3422),
                            Description = "",
                            Icon = "InProgress",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3419),
                            Status = "In Progress"
                        },
                        new
                        {
                            ID = 3,
                            Color = "Success",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3432),
                            Description = "",
                            Icon = "Completed",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3429),
                            Status = "Completed"
                        },
                        new
                        {
                            ID = 4,
                            Color = "Danger",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3442),
                            Description = "",
                            Icon = "Cancelled",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3439),
                            Status = "Cancelled"
                        },
                        new
                        {
                            ID = 5,
                            Color = "Danger",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3451),
                            Description = "",
                            Icon = "Rejected",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3448),
                            Status = "Rejected"
                        },
                        new
                        {
                            ID = 6,
                            Color = "Success",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3461),
                            Description = "",
                            Icon = "Approved",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3458),
                            Status = "Approved"
                        },
                        new
                        {
                            ID = 7,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3470),
                            Description = "",
                            Icon = "OnHold",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3467),
                            Status = "On Hold"
                        },
                        new
                        {
                            ID = 8,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3480),
                            Description = "",
                            Icon = "NotStarted",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3477),
                            Status = "Not Started"
                        },
                        new
                        {
                            ID = 9,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3489),
                            Description = "",
                            Icon = "NotApplicable",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3486),
                            Status = "Not Applicable"
                        },
                        new
                        {
                            ID = 10,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3499),
                            Description = "",
                            Icon = "NotRequired",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3495),
                            Status = "Not Required"
                        },
                        new
                        {
                            ID = 11,
                            Color = "Warning",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3508),
                            Description = "",
                            Icon = "NotAvailable",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3505),
                            Status = "Not Available"
                        });
                });

            modelBuilder.Entity("PM_DataAccess.StagesClasses.StageTypes", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StageID");

                    b.ToTable("StageTypes");

                    b.HasData(
                        new
                        {
                            StageID = 1,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3567),
                            Description = "",
                            Duration = 0,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "Intake",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3570),
                            Name = "Intake",
                            Order = "",
                            Parent = "",
                            Responsible = "Referrer"
                        },
                        new
                        {
                            StageID = 2,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3579),
                            Description = "",
                            Duration = 7,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "Assessment",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3582),
                            Name = "SocioEconomic Assessment",
                            Order = "",
                            Parent = "",
                            Responsible = "Social Worker"
                        },
                        new
                        {
                            StageID = 3,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3587),
                            Description = "",
                            Duration = 7,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "Medical",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3590),
                            Name = "Medical Assessment",
                            Order = "",
                            Parent = "",
                            Responsible = "Medical Examiner"
                        },
                        new
                        {
                            StageID = 4,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3594),
                            Description = "",
                            Duration = 7,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "Treatment",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3597),
                            Name = "Treatment Plan",
                            Order = "",
                            Parent = "",
                            Responsible = "HealthCare Service Providers"
                        },
                        new
                        {
                            StageID = 5,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3601),
                            Description = "",
                            Duration = 7,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "Financial",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3603),
                            Name = "Payment Stage",
                            Order = "",
                            Parent = "",
                            Responsible = "Medi-financial service provider"
                        },
                        new
                        {
                            StageID = 6,
                            Color = "Green",
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3608),
                            Description = "",
                            Duration = 0,
                            DurationType = "",
                            DurationUnit = "Day",
                            Group = "",
                            Icon = "End",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3610),
                            Name = "End the process",
                            Order = "",
                            Parent = "",
                            Responsible = "Admin"
                        });
                });

            modelBuilder.Entity("PM_DataAccess.UserProfiles.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserProfile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PM_DataAccess.UserProfiles.UserType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2971),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2966),
                            Type = "Referrer"
                        },
                        new
                        {
                            ID = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2982),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2979),
                            Type = "Social Worker"
                        },
                        new
                        {
                            ID = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2992),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2988),
                            Type = "Medical Examiner"
                        },
                        new
                        {
                            ID = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3001),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(2998),
                            Type = "HealthCare Service Providers"
                        },
                        new
                        {
                            ID = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3010),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3007),
                            Type = "Financial Supporter"
                        },
                        new
                        {
                            ID = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3019),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3016),
                            Type = "Medical Missions"
                        },
                        new
                        {
                            ID = 7,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3028),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3025),
                            Type = "Medi-financial service provider"
                        },
                        new
                        {
                            ID = 8,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3038),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            IsModified = false,
                            ModifiedBy = "",
                            ModifiedDate = new DateTime(2024, 8, 7, 15, 0, 45, 788, DateTimeKind.Local).AddTicks(3035),
                            Type = "Admin"
                        });
                });

            modelBuilder.Entity("PM_Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PM_DataAccess.Referrer.Referrer", b =>
                {
                    b.HasBaseType("PM_DataAccess.UserProfiles.UserProfile");

                    b.HasDiscriminator().HasValue("Referrer");
                });

            modelBuilder.Entity("PM_DataAccess.SocialWorker.SocialWorker", b =>
                {
                    b.HasBaseType("PM_DataAccess.UserProfiles.UserProfile");

                    b.HasDiscriminator().HasValue("SocialWorker");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PM_Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PM_Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PM_Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PM_DataAccess.PatientClasses.Patient", b =>
                {
                    b.HasOne("PM_DataAccess.Referrer.Referrer", null)
                        .WithMany("Patients")
                        .HasForeignKey("ReferrerID");

                    b.HasOne("PM_DataAccess.SocialWorker.SocialWorker", null)
                        .WithMany("Patients")
                        .HasForeignKey("SocialWorkerID");
                });

            modelBuilder.Entity("PM_DataAccess.SEA.SocioeconomicAssessment", b =>
                {
                    b.HasOne("PM_DataAccess.GeneInfo.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_DataAccess.PatientClasses.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PM_DataAccess.StagesClasses.Stage", b =>
                {
                    b.HasOne("PM_DataAccess.PatientClasses.Patient", null)
                        .WithMany("Stages")
                        .HasForeignKey("PatientID");
                });

            modelBuilder.Entity("PM_DataAccess.PatientClasses.Patient", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("PM_DataAccess.Referrer.Referrer", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PM_DataAccess.SocialWorker.SocialWorker", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
